add test checking weather_dist files
deeppavlovteam/deeppavlov_dreamtools pull request #1
Opened 2022-09-06 15:32 UTC by ilyazat

2022-09-06 16:16 UTC, mtalimanchuk requested changes
Мы должны тестить не просто файлы, а результат работы программы, т.е. с помощью dreamtools надо сгенерить эти конфиги, а потом сверять их с ground truth.

2022-09-06 16:16 UTC, mtalimanchuk commented on deeppavlov_dreamtools/tests/test_distweather.py
> +    dream_path_dist = Path(Path().absolute().parents[2]) / "dream" / "assistant_dists" / "dream_weather"
не нужно оборачивать родителей в Path - он уже такого типа
`dream_path_dist = Path().absolute().parents[2] / "dream" / "assistant_dists" / "dream_weather"`

2022-09-06 16:16 UTC, mtalimanchuk commented on deeppavlov_dreamtools/tests/test_distweather.py
> +    dream_path_dist = Path(Path().absolute().parents[2]) / "dream" / "assistant_dists" / "dream_weather"
не нужно оборачивать родителей в Path - он уже такого типа
`dream_path_dist = Path().absolute().parents[2] / "dream" / "assistant_dists" / "dream_weather"`

2022-09-06 16:16 UTC, mtalimanchuk commented on deeppavlov_dreamtools/tests/test_distweather.py
> +    :param file: name of file
мы используем google-style docstrings, посмотри в distconfigs/manager.py примеры

2022-09-06 16:16 UTC, mtalimanchuk commented on requirements.txt
> +pytest==7.1.2
создай отдельный файл `test-requirements.txt`, туда добавь пайтест и все из обычного requirements, потому что для работы dreamtools этот пакет не нужен

2022-09-07 07:21 UTC, ilyazat commented
While building pytest found out that docker-compose.override.yml and proxy.yml are not equal to ground_truth

2022-09-07 07:22 UTC, merged